#[shell]
#program = "/usr/bin/tmux"
#args = ["-u"] # force UTF-8 in tmux

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"		# contains all characters used as separators for "semantic words" in Alacritty.
save_to_clipboard = true 				# When set to `true`, selected text will be copied to the primary clipboard.

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]


[window]
opacity = 0.95
blur = true
dynamic_padding = false
decorations = "None" # "Full" | "None" | "Transparent" | "Buttonless"
decorations_theme_variant = "Dark" # "Light"

[window.padding]
x = 10
y = 10


[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"


#import = [
#	"~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
#]

# Base16 Default Dark - alacritty color config
# Chris Kempson (http://chriskempson.com)
# 
# [colors]
# draw_bold_text_with_bright_colors = true
# 
# # Default colors
# [colors.primary]
# background = '0x181818'
# foreground = '0xd8d8d8'
# 
# # Colors the cursor will use if `custom_cursor_colors` is true
# [colors.cursor]
# text = '0x181818'
# cursor = '0xd8d8d8'
# 
# # Normal colors
# [colors.normal]
# black = '0x181818'
# red = '0xab4642'
# green = '0xa1b56c'
# yellow = '0xf7ca88'
# blue = '0x7cafc2'
# magenta = '0xba8baf'
# cyan = '0x86c1b9'
# white = '0xd8d8d8'
# 
# # Bright colors
# [colors.bright]
# black = '0x585858'
# red = '0xdc9656'
# green = '0x282828'
# yellow = '0x383838'
# blue = '0xb8b8b8'
# magenta = '0xe8e8e8'
# cyan = '0xa16946'
# white = '0xf8f8f8'

